### ISSUE TITLE
Progress: Migration from Parse to Gists

### ISSUE THREAD

**Issue by fkling** [fkling/astexplorer#184]
This issue will outline the steps I am going to take to move away from Parse.

### Context
Parse is discontinuing its service on January 28th. As explained in #142, I am planning to use gists as storage instead. The linked issue explains the advantages that gists have.

### astexplorer server
Using the GitHub API requires to send authentication tokens (either received via OAuth or otherwise) or similar sensitive information. For me, the easiest way to get this to work is to run a server for astexplorer. Having our own server has other advantages as well. For example, we could add support for parsers that are not implemented in JavaScript.  
I will be paying for the server myself at first and will look for other financing options in the future.

### How will code snippets be saved as gists?
At the beginning, all snippets will be saved as *secret* gists owned by the *astexplorer* user, that I created specifically for this. A gist will have up to three files:

- `astexplorer.json`: Containing configuration and settings, such as the parser that is used.
- `code.js`: The code that is parsed.
- `transform.js`: If a transform/tool is selected, this file contains the code of the transform.

Example: https://gist.github.com/astexplorer/28ae2bb52426fa497264674356d0341a

A snippet can then be accessed via a URL similar to
```
https://astexplorer.net/#/gist/28ae2bb52426fa497264674356d0341a/407c5e81320b3bf6a07117e191d4a45936d1f772
```

The first part is the hash of the gist, the second part the hash of the revision. I know the URLs are long and ugly. Maybe we can eventually offer to create short URLs to specific revisions.

**Note:** Everybody that has a URL to such as snippet will be able to add a new revision, just like it works now.

### Can I save the snippets to my GitHub account?
Eventually yes. The first priority is to ensure that astexplorer continues to work. Being able to authenticate will be added later.
The advantage of saving snippets to your account is that only you can add new revisions.

### What happens to the existing code snippets?
Existing URLs and snippets will continue to work. After considering various options, I think the easiest solution is to export the existing data and simply store the exported files on the server and serve them from there.  
Maybe the snippets will be migrated to gists eventually, but that's not a priority.

**Note:** Existing snippets will be loaded "read-only". Changes can only be made by forking the snippet (in which case it will be saved as gist). The UI will point that out.

#### Phase 1
- [x] Deploy server with gist API
- [x] Deploy new site that loads existing snippets read only and stores new snippets in gists

#### Phase 2
- [x] Export final Parse dataset
- [x] Deploy new server version that can serve parse snippets from the  exported files
- [x] Deploy new site that loads parse snippets from server

#### Phase 3
- [ ] Add authentication via GitHub, allow snippets to be stored to authenticated user

---

Please let me know if you have any questions or suggestions!

**Comment by hzoo** [comment]
> I will be paying for the server myself at first and will look for other financing options in the future.

Can do an open collective 😄 or we can send you some when Babel does one?

> Note: Everybody that has a URL to such as snippet will be able to add a new revision, just like it works now.

Is there a way to check the previous versions like a diff (there's no diff now but you can just go back since its incrementing by a number)

**Comment by giuseppeg** [comment]
@fkling I would like to thank you prematurely for this, it is going to require some work :)
Do you think that it'd be possible to prefix each file/gist name with `astexporer_`? They are going to add noise to the gists archive page.

**Comment by suchipi** [comment]
I would love to donate to server costs at some point. I use this tool a lot

**Comment by fkling** [comment]
@hzoo That's a great idea, I will keep that in mind!

> Is there a way to check the previous versions like a diff

Gists have a history view built-in, e.g.

<img width="1015" alt="screen shot 2017-01-19 at 8 07 08 am" src="https://cloud.githubusercontent.com/assets/179026/22114458/61d8f158-de1e-11e6-944e-f6610aae05da.png">


We can also get that data via the API and show some kind of history in astexplorer itself (which would allow you to easily jump between revisions). It's probably not *that* useful for unauthenticated snippets (i.e. snippets owned by the astexplorer user), since everybody can make changes, but it will certainly be useful for authenticated snippets.

Some other nice things to have:

- Link inside astexplorer that links to the corresponding gist
- A bookmarklet or something similar that lets you open astexplorer for a gist
- Show gist comments in astexplorer (unclear how that works for revisions)

So, at first it will be a bit less convenient to switch between revisions, but I hope we can work together to improve this.

---

@giuseppeg: Thank you 😃 It appears that GitHub sorts files alphabetically and always shows the first file in the list view. Therefore the `astexplorer.json` file would automatically be the first file. E.g. for the astexplorer user it looks like this:

<img width="1006" alt="screen shot 2017-01-19 at 8 17 27 am" src="https://cloud.githubusercontent.com/assets/179026/22114876/ccf4821c-de1f-11e6-9013-37187d5b3e16.png">

Wouldn't that suffice? Originally I thought it would nice see the actual code in the overview, but I don't want to give the files arbitrary names just to make them appear in a specific order.

---

Thank you @suchipi, I really appreciate that!

**Comment by giuseppeg** [comment]
Yeah that should work, my issue with services that use github's gists for storage is that those gists add noise and mix up with my "real" gists in the all gists page

**Comment by skratchdot** [comment]
I'm glad you are prefixing this new functionality with `/#/gist/` in the url because that will allow for future import/export types if we ever need it.  I think it's important enough to call out / `+1` :)

I'm also thankful for your work on this project and don't want to see you having to pay for server costs.  Perhaps you should throw up some donation buttons in the readme (OpenCollective, Paypal, etc).

**Comment by fkling** [comment]
@giuseppeg: I see. It's not possible to create gists associated with your user account atm anyway. And even if it is possible, you don't have to use that option. You can always create gists that are owned by the astexplorer user.

@skratchdot: That was the plan 😃 I was also considering adding versioning too, e.g. `/#/v1/gist/`, but not sure if that's too much... what do you think?

Regarding donations: We will do that eventually. I don't expect costs to be high for now. I first want to get everything working properly.

**Comment by skratchdot** [comment]
@fkling - Well, you did add a version key in the astexplorer.json example, so I think if it's there, then that's good.  Having it in the url would allow you to change how/where you load the gist files, but you could always update the format in "v2" (if that ever comes).  i.e. v1 urls look like `/#/gist/` and v2 urls could look like `/#/v2/gist/`.

So my long winded answer: I like the way you have it now 😃

**Comment by skratchdot** [comment]
2.0.0 release notes are looking good 👍 https://github.com/fkling/astexplorer/releases/tag/v2.0.0

**Comment by fkling** [comment]
@skratchdot Thank you 😃 

I swear I tested everything. If anybody encounters errors, please create an issue (or PR 😉 ).

The plan is to download a final data dump from parse on Sunday and then serve that data from astexplorer's own server.

**Comment by Turbo87** [comment]
@fkling seems to work well so far. nice work!

**Comment by fkling** [comment]
Parse snippets are now served from the astexplorer server 🎉 .

Unfortunately it wasn't possible to simply export a final dataset. I had to spin up a mongoDB and use the migration service Parse offered. The data transfer was really quick though. No new snippets have been created in Parse since the astexplorer update rolled out.

I don't know when I'm going to implement the user authentication part (if someone wants to take stab at it, go for it!), probably *not* within the next two weeks. Last week was pretty exhausting, so I'm going to take it slow for a bit.

However, I will start writing down some ideas about what could be next for astexplorer.

Thank you for all the encouraging words and for using astexplorer!
